#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if command -v wslview >/dev/null 2>&1; then
    wslview "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  elif command -v explorer.exe >/dev/null 2>&1; then
    explorer.exe "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  elif command -v open >/dev/null 2>&1; then
    open "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  else
    warn "couldn't open a browser — visit it manually: $url"
  fi
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { warn "invalid environment key: $key"; return 1; }
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || { warn "refusing multiline value for $key"; return 1; }
  touch "$ENV_FILE"
  tmp=$(mktemp)
  if grep -vE "^${key}=" "$ENV_FILE" > "$tmp"; then
    :
  else
    local grep_status=$?
    if [[ "$grep_status" -ne 1 ]]; then
      rm -f "$tmp"
      warn "couldn't read $ENV_FILE safely; leaving it unchanged"
      return "$grep_status"
    fi
  fi
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${WIZARD_STATE_FILE:-$HOME/.veille-scientifique-installer.env}"
REPOSITORY_ARCHIVE="https://github.com/DimitriNaczaj/veille-scientifique/archive/refs/heads/main.tar.gz"
umask 077

banner "Installation NAS · Veille scientifique Bellegarde"

stage "Pré-requis du NAS"
say "Vérification de Bash, Python 3.8+, SQLite, TLS et des outils d’installation."
[[ -n "${BASH_VERSION:-}" ]] || { warn "Ce script doit être lancé avec Bash."; exit 1; }
command -v tar >/dev/null 2>&1 || { warn "La commande tar est absente."; exit 1; }
PYTHON_BIN=""
for candidate in \
  "$(command -v python3.9 2>/dev/null || true)" \
  "$(command -v python3 2>/dev/null || true)" \
  /var/packages/py3k/target/usr/local/bin/python3 \
  /var/packages/Python3.9/target/usr/local/bin/python3.9; do
  if [[ -n "$candidate" && -x "$candidate" ]] && \
     "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 8) else 1)' 2>/dev/null; then
    PYTHON_BIN="$candidate"
    break
  fi
done
if [[ -z "$PYTHON_BIN" ]]; then
  ask PYTHON_BIN "Chemin absolu de Python 3.9 :"
fi
[[ -x "$PYTHON_BIN" ]] || { warn "Python n’est pas exécutable : $PYTHON_BIN"; exit 1; }
[[ "$PYTHON_BIN" != *$'\n'* && "$PYTHON_BIN" != *"'"* ]] || {
  warn "Le chemin de Python contient un caractère non pris en charge."
  exit 1
}
"$PYTHON_BIN" -c 'import imaplib, json, sqlite3, ssl, smtplib, sys; print(sys.version.split()[0])'
write_env PYTHON_BIN "$PYTHON_BIN"
chmod 600 "$ENV_FILE"
say "Python et les modules requis sont disponibles."

stage "Dossier d’installation"
ask INSTALL_ROOT "Dossier cible [Entrée = /volume1/Bellegarde/veille-scientifique] :"
INSTALL_ROOT=${INSTALL_ROOT:-/volume1/Bellegarde/veille-scientifique}
[[ "$INSTALL_ROOT" == /* ]] || { warn "Le dossier cible doit être absolu."; exit 1; }
[[ "$INSTALL_ROOT" != "/" && ! "$INSTALL_ROOT" =~ ^/volume[0-9]+$ ]] || {
  warn "Dossier cible trop large : $INSTALL_ROOT"
  exit 1
}
[[ "$INSTALL_ROOT" != *$'\n'* && "$INSTALL_ROOT" != *"'"* ]] || {
  warn "Le dossier cible contient un caractère non pris en charge."
  exit 1
}
say "Cible : $INSTALL_ROOT"
confirm "Créer ou mettre à jour ce dossier ?" || { warn "Installation annulée."; exit 1; }
mkdir -p "$INSTALL_ROOT" || {
  warn "Impossible d’écrire dans $INSTALL_ROOT. Vérifiez les permissions DSM."
  exit 1
}
INSTALL_ROOT=$(cd "$INSTALL_ROOT" && pwd -P)
[[ "$INSTALL_ROOT" != "/" && ! "$INSTALL_ROOT" =~ ^/volume[0-9]+$ ]] || {
  warn "Le chemin résolu est trop large : $INSTALL_ROOT"
  exit 1
}
write_env INSTALL_ROOT "$INSTALL_ROOT"
chmod 600 "$ENV_FILE"

stage "Téléchargement du projet"
say "Téléchargement de la branche main depuis GitHub, sans inclure aucun secret."
DOWNLOAD_DIR=$(mktemp -d "${TMPDIR:-/tmp}/veille-install.XXXXXX")
cleanup_download() {
  if [[ -n "${DOWNLOAD_DIR:-}" && "$DOWNLOAD_DIR" == "${TMPDIR:-/tmp}"/veille-install.* ]]; then
    rm -rf -- "$DOWNLOAD_DIR"
  fi
}
trap cleanup_download EXIT
ARCHIVE_PATH="$DOWNLOAD_DIR/veille.tar.gz"
if command -v curl >/dev/null 2>&1; then
  curl --fail --location --silent --show-error "$REPOSITORY_ARCHIVE" --output "$ARCHIVE_PATH"
elif command -v wget >/dev/null 2>&1; then
  wget -q "$REPOSITORY_ARCHIVE" -O "$ARCHIVE_PATH"
else
  "$PYTHON_BIN" -c \
    'import sys, urllib.request; urllib.request.urlretrieve(sys.argv[1], sys.argv[2])' \
    "$REPOSITORY_ARCHIVE" "$ARCHIVE_PATH"
fi
tar -xzf "$ARCHIVE_PATH" -C "$DOWNLOAD_DIR"
SOURCE_DIR="$DOWNLOAD_DIR/veille-scientifique-main"
[[ -f "$SOURCE_DIR/pyproject.toml" && -f "$SOURCE_DIR/veille/__main__.py" ]] || {
  warn "L’archive téléchargée ne contient pas le projet attendu."
  exit 1
}
cp -R "$SOURCE_DIR"/. "$INSTALL_ROOT"/
chmod +x "$INSTALL_ROOT/scripts/run-daily.sh" "$INSTALL_ROOT/scripts/install-nas.sh"
touch "$INSTALL_ROOT/.veille-installation"
mkdir -p \
  "$INSTALL_ROOT/inbox" \
  "$INSTALL_ROOT/data" \
  "$INSTALL_ROOT/out" \
  "$INSTALL_ROOT/import" \
  "$INSTALL_ROOT/smoke"
say "Projet installé depuis GitHub."

stage "Configuration privée"
CONFIG_PATH="$INSTALL_ROOT/veille-scientifique.ini"
REUSE_CONFIG=false
if [[ -f "$CONFIG_PATH" ]] && confirm "Réutiliser la configuration privée existante ?"; then
  REUSE_CONFIG=true
fi
if [[ "$REUSE_CONFIG" == false ]]; then
  ask MAIL_USERNAME "Adresse de la boîte scientifique [Entrée = science-digest@bellegarde.co] :"
  MAIL_USERNAME=${MAIL_USERNAME:-science-digest@bellegarde.co}
  ask DIGEST_RECIPIENT "Adresse qui recevra le futur digest :"
  [[ "$MAIL_USERNAME" == *@* && "$DIGEST_RECIPIENT" == *@* ]] || {
    warn "Les deux adresses doivent être valides."
    exit 1
  }
  MAIL_USERNAME_NORMALIZED=$(printf '%s' "$MAIL_USERNAME" | tr '[:upper:]' '[:lower:]')
  DIGEST_RECIPIENT_NORMALIZED=$(printf '%s' "$DIGEST_RECIPIENT" | tr '[:upper:]' '[:lower:]')
  [[ "$MAIL_USERNAME_NORMALIZED" != "$DIGEST_RECIPIENT_NORMALIZED" ]] || {
    warn "Le destinataire réel doit être différent de la boîte de test."
    exit 1
  }
  ask_secret MAIL_PASSWORD "Mot de passe actuel de la boîte (saisie masquée) :"
  [[ -n "$MAIL_PASSWORD" && "$MAIL_PASSWORD" != *$'\r'* ]] || {
    warn "Le mot de passe est vide ou contient un retour chariot."
    exit 1
  }
  CONFIG_TMP="$CONFIG_PATH.tmp.$$"
  {
    printf '%s\n' '[imap]'
    printf '%s\n' 'host = mail.infomaniak.com' 'port = 993'
    printf 'username = %s\npassword = %s\n' "$MAIL_USERNAME" "$MAIL_PASSWORD"
    printf '%s\n\n' 'folder = Articles' 'initial_mode = latest'
    printf '%s\n' '[smtp]' 'host = mail.infomaniak.com' 'port = 587' 'security = starttls'
    printf 'from_address = %s\ntest_recipient = %s\n\n' "$MAIL_USERNAME" "$MAIL_USERNAME"
    printf '%s\n' '[digest]'
    printf 'recipient = %s\nfrom_address = %s\n' "$DIGEST_RECIPIENT" "$MAIL_USERNAME"
    printf '%s\n\n' 'subject_prefix = Veille scientifique Bellegarde'
    printf '%s\n' '[app]'
    printf 'inbox = %s/inbox\ndatabase = %s/data/veille.sqlite\noutput = %s/out/digest.html\n' \
      "$INSTALL_ROOT" "$INSTALL_ROOT" "$INSTALL_ROOT"
    printf 'crossref_email = %s\n' "$MAIL_USERNAME"
    printf '%s\n\n' 'sync_limit = 200' 'enrichment_limit = 100' 'ai_limit = 30'
    printf '%s\n' '[ai]' 'enabled = true' 'model = gpt-5.6-luna' 'api_key_env = OPENAI_API_KEY'
  } > "$CONFIG_TMP"
  chmod 600 "$CONFIG_TMP"
  mv "$CONFIG_TMP" "$CONFIG_PATH"
  write_env MAIL_USERNAME "$MAIL_USERNAME"
  write_env DIGEST_RECIPIENT "$DIGEST_RECIPIENT"
  chmod 600 "$ENV_FILE"
  unset MAIL_PASSWORD
fi
chmod 600 "$CONFIG_PATH"
say "Configuration écrite avec permissions 600. Aucun secret n’est envoyé à GitHub."

stage "Tests automatisés"
say "Exécution des tests synthétiques, sans réseau ni envoi."
(
  cd "$INSTALL_ROOT"
  "$PYTHON_BIN" -m unittest discover -s tests -v
  "$PYTHON_BIN" -m compileall -q veille tests
)
say "Les tests automatisés sont réussis."

stage "Diagnostics de la boîte"
say "IMAP sera ouvert en lecture seule. SMTP s’authentifiera sans envoyer de message."
(
  cd "$INSTALL_ROOT"
  "$PYTHON_BIN" -m veille test-imap --config "$CONFIG_PATH"
  "$PYTHON_BIN" -m veille test-smtp --config "$CONFIG_PATH"
)
say "IMAP et SMTP sont accessibles depuis le NAS."

stage "Recette quotidienne isolée"
say "Une base temporaire distincte va ignorer l’historique et n’enverra aucun courriel."
SMOKE_ROOT="$INSTALL_ROOT/smoke/run-$(date +%Y%m%d-%H%M%S)-$$"
mkdir -p "$SMOKE_ROOT/inbox" "$SMOKE_ROOT/out"
(
  cd "$INSTALL_ROOT"
  "$PYTHON_BIN" -m veille daily \
    --config "$CONFIG_PATH" \
    --inbox "$SMOKE_ROOT/inbox" \
    --database "$SMOKE_ROOT/veille.sqlite" \
    --output "$SMOKE_ROOT/out/digest.html" \
    --sync-limit 1 \
    --initial-mode latest \
    --enrichment-limit 1 \
    --ai-limit 0 \
    --no-ai \
    --no-send
)
[[ -f "$SMOKE_ROOT/out/digest.html" ]] || {
  warn "Le digest de recette n’a pas été généré."
  exit 1
}
say "Recette réussie : $SMOKE_ROOT/out/digest.html"

stage "Courriel de contrôle et prochaine étape"
say "La tâche quotidienne DSM ne sera pas créée ni activée par cet assistant."
if confirm "Envoyer maintenant un unique courriel SMTP de contrôle à la boîte scientifique ?"; then
  (
    cd "$INSTALL_ROOT"
    "$PYTHON_BIN" -m veille test-smtp --config "$CONFIG_PATH" --send-test
  )
else
  SKIPPED+=("courriel SMTP de contrôle")
fi
TASK_COMMAND_FILE="$INSTALL_ROOT/DSM_TASK_COMMAND.txt"
printf "VEILLE_ROOT='%s' PYTHON_BIN='%s' '%s/scripts/run-daily.sh'\n" \
  "$INSTALL_ROOT" "$PYTHON_BIN" "$INSTALL_ROOT" > "$TASK_COMMAND_FILE"
chmod 600 "$TASK_COMMAND_FILE"
step "Après sécurisation des secrets, ouvrez DSM → Panneau de configuration → Planificateur de tâches."
step "Créez une tâche définie par l’utilisateur et copiez la commande de $TASK_COMMAND_FILE."
warn "N’activez pas encore cette tâche : nous sécuriserons d’abord le mot de passe et ajouterons la clé OpenAI."

finish
note "Installation : $INSTALL_ROOT"
note "Configuration privée : $CONFIG_PATH"
note "Dernière recette : $SMOKE_ROOT"
note "Commande DSM préparée : $TASK_COMMAND_FILE"
